"use client";
import { QueryClientProvider } from "@tanstack/react-query";
import { Flex, MantineProvider, Stack } from "@mantine/core";
import { queryClient } from "@/lib/queryClient";
import { Provider } from "react-redux";
import store from "@/redux/store";
import { usePathname } from "next/navigation";
import "@mantine/notifications/styles.css";
import "@mantine/carousel/styles.css";
import { Notifications } from "@mantine/notifications";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <QueryClientProvider client={queryClient}>
      <Notifications position="top-center" />
      <Provider store={store}>
        <Flex align={"Flex-center"} justify={"center"} w={"100%"}>
          <Stack>{children}</Stack>
        </Flex>
      </Provider>
    </QueryClientProvider>
  );
}
