"use client";
import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import "mantine-datatable/styles.layer.css";
import { usePathname } from "next/navigation";

import {
  Heebo,
  Urbanist,
  Space_Grotesk,
  Tangerine, // Clean, modern geometric
} from "next/font/google";
import { Notifications } from "@mantine/notifications";
import GoogleAnalytics from "@/components/common/GAnalytics";

const spaceGrotesk = Heebo({
  subsets: ["latin"],
  weight: ["400", "600"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={`${spaceGrotesk.className} antialiased `}>
        <GoogleAnalytics />
        {children}
      </body>
    </html>
  );
}
